[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173 # Vite's default port
  publish = "dist"
  framework = "vite"
  autoLaunch = true
  envFiles = [".env", ".env.development"] # Specify all env files to load

[functions]
  directory = "netlify/functions"
  included_files = [".env", ".env.development"]
  node_bundler = "esbuild"

[build.environment]
  NODE_ENV = "development"

[dev.environment]
  PIT = "${VITE_PIT}"
  VITE_PIT = "${VITE_PIT}"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
